console.log("Mohit Jha is a front end developer")
console.log("Mohit Jha is a front end developer")
console.log("Mohit Jha is a front end developer")
console.log("Mohit Jha is a front end developer")
console.log("Mohit Jha is a front end developer")